### ISSUE TITLE
Update to newest libraries

### ISSUE THREAD

**Issue by Juleffel** [pesterhazy/double-bundle#2]
Hi ! I tried by all means during an entire day to use this method/update this directory to use latest versions of reagent/react, and failed. I still have errors in the browser console and nothing works correctly. I would really appreciate if someone with some knowledge around these things can give it a try. I also try the :foreign-libs methods or the :npm-deps method but without anymore success :/

Here is my current try on this method:
https://github.com/Juleffel/double-bundle/tree/reagent-0.8.1

**Comment by pesterhazy** [comment]
Hi @Juleffel thanks for your input!

I've published a new starter project called cljs-spa-example which uses uptodate versions of Reagent, ClojureScript etc. It also uses Figwheel Main. Please check it out

**Comment by pesterhazy** [comment]
Here's a link

I've added a deprecation notice to the README
